<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.TestUtilities" Version="2.0.0" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.13.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\api\SentinelOps.Api.csproj" />
    <ProjectReference Include="..\workers\SentinelOps.Events\SentinelOps.Events.csproj" />
    <ProjectReference Include="..\workers\SentinelOps.Workers.Shared\SentinelOps.Workers.Shared.csproj" />
    <ProjectReference Include="..\workers\SentinelOps.Workers.AlertValidation\SentinelOps.Workers.AlertValidation.csproj" />
    <ProjectReference Include="..\workers\SentinelOps.Workers.Deduplication\SentinelOps.Workers.Deduplication.csproj" />
    <ProjectReference Include="..\workers\SentinelOps.Workers.IncidentCreation\SentinelOps.Workers.IncidentCreation.csproj" />
    <ProjectReference Include="..\workers\SentinelOps.Workers.ResponderAssignment\SentinelOps.Workers.ResponderAssignment.csproj" />
    <ProjectReference Include="..\workers\SentinelOps.Workers.Notification\SentinelOps.Workers.Notification.csproj" />
    <ProjectReference Include="..\workers\SentinelOps.Workers.Analytics\SentinelOps.Workers.Analytics.csproj" />
    <ProjectReference Include="..\workers\SentinelOps.Workers.AuditLog\SentinelOps.Workers.AuditLog.csproj" />
    <ProjectReference Include="..\workers\SentinelOps.Workers.Escalation\SentinelOps.Workers.Escalation.csproj" />
    <ProjectReference Include="..\workers\SentinelOps.Workers.Dashboard\SentinelOps.Workers.Dashboard.csproj" />
  </ItemGroup>

</Project>
